openapi: 3.0.1
info:
  title: booknaav-backend
  description: backend for booknaav app in typescipt
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification
paths:
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}

  /users/otp:
    post:
      tags:
        - Login OTP
      description: login user with OTP
      requestBody:
        description: Send OTP to login user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginBody'
        required: true
      responses:
        200:
          description: Return the example with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users/verify:
    post:
      tags:
        - Verify User
      description: Verify user
      requestBody:
        description: Verify login with otp
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyUserBody'
      responses:
        200:
          description: Return the example with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users/refresh:
    post:
      tags:
        - Refresh token
      description: Refresh token user
      responses:
        200:
          description: Return the example with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/logout:
    get:
      tags:
        - Logout User
      description: Logout user
      responses:
        200:
          description: Return the example with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/all:
    get:
      tags:
        - Give all users
      description: Return all users
      responses:
        200:
          description: Return all users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/me:
    get:
      tags:
        - Logged in User
      description: LoggedIn user
      responses:
        200:
          description: Return the example with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/update:
    post:
      tags:
        - Update logged in user
      description: Update logged in user
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                picture:
                  type: string
                  format: binary
      responses:
        200:
          description: Return the example with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users/register:
    post:
      tags:
        - Register
      description: Register user
      requestBody:
        description: Register user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterBody'
        required: true
      responses:
        200:
          description: Return the example with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /ghat/:id:
    get:
      tags:
        - Ghat
      description: Return ghat with the specified id
      responses:
        200:
          description: Return the example with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Ghat
      description: Update ghat with the specified id
      requestBody:
        description: Update ghat with the specified id
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GhatBody'
        required: true
      responses:
        200:
          description: Return the example with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /ghat:
    get:
      tags:
        - Ghat
      description: Return all ghat
      responses:
        200:
          description: Return all ghat
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Ghat
      description: Create ghat
      requestBody:
        description: Create ghat
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GhatBody'
        required: true
      responses:
        200:
          description: Return the example with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Example:
      type: object
      properties:
        id:
          type: integer
          example: 3
        name:
          type: string
          example: example 3
    Error:
      type: object
      additionalProperties: true

    ExampleBody:
      title: example
      required:
        - name
      type: object
      properties:
        name:
          type: string
          example: no_stress

    RegisterBody:
      title: register
      required:
        - title
        - phone
      type: object
      properties:
        title:
          type: string
          example: no_stress
        phone:
          type: string
          example: +919012345678

    LoginBody:
      title: login
      required:
        - phone
      type: object
      properties:
        phone:
          type: string
          example: +62812341234

    VerifyUserBody:
      title: verify user
      required:
        - phone
        - otp
        - hash
      type: object
      properties:
        hash:
          type: string
          example: hash
        phone:
          type: string
          example: +62812341234
        otp:
          type: string
          example: 123456
    GhatBody:
      title: ghat add
      required:
        - name
      type: object
      properties:
        name:
          type: string
          example: no_stress
        description:
          type: string
          example: no_stress
        picture:
          type: string
          format: binary
          example: picture
        location:
          type: object
          properties:
            lat:
              type: number
              example: -6.914744
            lng:
              type: number
              example: 107.609810
